export const password = {
  spaces: 0,
  lowerCase: 1,
  upperCase: 1,
  number: 1,
  symbol: 1,
};
export const user = {
  spaces: 0,
  lowerCase: -1,
  upperCase: -1,
  number: -1,
  symbol: 0,
  forbidden: [
    'Cabron',
    'puta',
    'Mamona',
    'gilipollas',
    'comepollas',
    'chupapollas',
    'comeculos',
    'maricon',
    'chupanabos',
    'comermierda',
    'carapolla',
    'follaculos',
    'follaviejas',
    'caraculo',
  ],
};
